### ISSUE TITLE
자연어 데이터 전처리

### ISSUE THREAD

**Issue by Worldofgentleken** [AICC-PFLOW/aiDev#2]
크롤링 데이터 학습 데이터에 맞도록 전처리 진행

**Comment by pythonize** [comment]
9/5 크롤링 데이터 바탕으로 칼럼별 전처리 진행하여 주요단어 리스트업 후 워드클라우드 완성하였습니다.(해당 자료실에 업로드)
현재는 사용자 입력정보에 맞춰 채용공고 페이지 추천할수 있도록 프로그램 작업중입니다.

**Comment by pythonize** [comment]
9/6 Wanted 크롤링 전체 데이터 바탕으로 전처리한 후 채용공고 페이지 추천기능 추가하였습니다
